# This is a basic workflow to help you get started with Actions
on:
  push:
    branches:
      - 'main'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: API - Install dependencies
        working-directory: api
        run: npm install
      - name: API - Test
        working-directory: api
        run: npm run test
  notify_failure:
    runs-on: ubuntu-latest
    needs: test
    if: failure()
    steps:
      - name: Send message to Discord
        run: |
          RANDOM_MESSAGE=https://official-joke-api.appspot.com/random_joke
          BRANCH_NAME=${GITHUB_REF##*/}
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"Tests failed on branch $BRANCH_NAME! $RANDOM_MESSAGE\"}" \
          ${{ secrets.DISCORD_LOG }}
