# This is a basic workflow to help you get started with Actions
on:
  push:
    branches:
      - 'main'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fail
        run: exit 1
  notify_failure:
    runs-on: ubuntu-latest
    needs: test
    if: failure()
    steps:
      - name: Send message to Discord
        run: |
          RANDOM_MESSAGE=$(curl -s "https://official-joke-api.appspot.com/random_joke")
          BRANCH_NAME=${GITHUB_REF##*/}
          SETUP=$(echo $RANDOM_MESSAGE | jq -r '.setup')
          PUNCHLINE=$(echo $RANDOM_MESSAGE | jq -r '.punchline')
          
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"FUCKING Tests failed on branch $BRANCH_NAME! $RANDOM_MESSAGE\"}" \
          ${{ secrets.DISCORD_LOG }}
